import "@/styles/globals.css";

import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/sooner";
import type { Metadata } from "next";
import { Cairo } from "next/font/google";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const cairo = Cairo({
    subsets: ["arabic"],
    variable: "--font-cairo",
    weight: ["300", "400", "500", "600", "700", "800"],
});

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html
            lang="en"
            className={`${cairo.className}`}
            suppressHydrationWarning
        >
            <body>
                <Providers>{children}</Providers>
                <Toaster richColors />
            </body>
        </html>
    );
}
